import { Word } from './types';

export const wordDatabase: Word[] = [
  // Easy words (200)
  { id: 'e1', word: 'cat', difficulty: 'easy', category: ['animals'] },
  { id: 'e2', word: 'dog', difficulty: 'easy', category: ['animals'] },
  { id: 'e3', word: 'sun', difficulty: 'easy', category: ['nature'] },
  { id: 'e4', word: 'tree', difficulty: 'easy', category: ['nature'] },
  { id: 'e5', word: 'book', difficulty: 'easy', category: ['objects'] },
  { id: 'e6', word: 'car', difficulty: 'easy', category: ['transportation'] },
  { id: 'e7', word: 'house', difficulty: 'easy', category: ['buildings'] },
  { id: 'e8', word: 'ball', difficulty: 'easy', category: ['sports', 'objects'] },
  { id: 'e9', word: 'bird', difficulty: 'easy', category: ['animals'] },
  { id: 'e10', word: 'fish', difficulty: 'easy', category: ['animals'] },
  { id: 'e11', word: 'moon', difficulty: 'easy', category: ['nature'] },
  { id: 'e12', word: 'star', difficulty: 'easy', category: ['nature'] },
  { id: 'e13', word: 'flower', difficulty: 'easy', category: ['nature'] },
  { id: 'e14', word: 'apple', difficulty: 'easy', category: ['food'] },
  { id: 'e15', word: 'banana', difficulty: 'easy', category: ['food'] },
  { id: 'e16', word: 'chair', difficulty: 'easy', category: ['furniture'] },
  { id: 'e17', word: 'table', difficulty: 'easy', category: ['furniture'] },
  { id: 'e18', word: 'door', difficulty: 'easy', category: ['objects'] },
  { id: 'e19', word: 'window', difficulty: 'easy', category: ['objects'] },
  { id: 'e20', word: 'phone', difficulty: 'easy', category: ['technology'] },
  { id: 'e21', word: 'clock', difficulty: 'easy', category: ['objects'] },
  { id: 'e22', word: 'bed', difficulty: 'easy', category: ['furniture'] },
  { id: 'e23', word: 'shoe', difficulty: 'easy', category: ['clothing'] },
  { id: 'e24', word: 'hat', difficulty: 'easy', category: ['clothing'] },
  { id: 'e25', word: 'eye', difficulty: 'easy', category: ['body'] },
  { id: 'e26', word: 'nose', difficulty: 'easy', category: ['body'] },
  { id: 'e27', word: 'ear', difficulty: 'easy', category: ['body'] },
  { id: 'e28', word: 'mouth', difficulty: 'easy', category: ['body'] },
  { id: 'e29', word: 'hand', difficulty: 'easy', category: ['body'] },
  { id: 'e30', word: 'foot', difficulty: 'easy', category: ['body'] },
  { id: 'e31', word: 'heart', difficulty: 'easy', category: ['body', 'shapes'] },
  { id: 'e32', word: 'rain', difficulty: 'easy', category: ['weather'] },
  { id: 'e33', word: 'snow', difficulty: 'easy', category: ['weather'] },
  { id: 'e34', word: 'cloud', difficulty: 'easy', category: ['weather'] },
  { id: 'e35', word: 'pizza', difficulty: 'easy', category: ['food'] },
  { id: 'e36', word: 'cake', difficulty: 'easy', category: ['food'] },
  { id: 'e37', word: 'ice cream', difficulty: 'easy', category: ['food'] },
  { id: 'e38', word: 'milk', difficulty: 'easy', category: ['food'] },
  { id: 'e39', word: 'water', difficulty: 'easy', category: ['drinks'] },
  { id: 'e40', word: 'juice', difficulty: 'easy', category: ['drinks'] },
  { id: 'e41', word: 'bread', difficulty: 'easy', category: ['food'] },
  { id: 'e42', word: 'cheese', difficulty: 'easy', category: ['food'] },
  { id: 'e43', word: 'egg', difficulty: 'easy', category: ['food'] },
  { id: 'e44', word: 'chicken', difficulty: 'easy', category: ['animals', 'food'] },
  { id: 'e45', word: 'cow', difficulty: 'easy', category: ['animals'] },
  { id: 'e46', word: 'pig', difficulty: 'easy', category: ['animals'] },
  { id: 'e47', word: 'horse', difficulty: 'easy', category: ['animals'] },
  { id: 'e48', word: 'sheep', difficulty: 'easy', category: ['animals'] },
  { id: 'e49', word: 'duck', difficulty: 'easy', category: ['animals'] },
  { id: 'e50', word: 'rabbit', difficulty: 'easy', category: ['animals'] },
  { id: 'e51', word: 'mouse', difficulty: 'easy', category: ['animals'] },
  { id: 'e52', word: 'lion', difficulty: 'easy', category: ['animals'] },
  { id: 'e53', word: 'tiger', difficulty: 'easy', category: ['animals'] },
  { id: 'e54', word: 'elephant', difficulty: 'easy', category: ['animals'] },
  { id: 'e55', word: 'monkey', difficulty: 'easy', category: ['animals'] },
  { id: 'e56', word: 'bear', difficulty: 'easy', category: ['animals'] },
  { id: 'e57', word: 'snake', difficulty: 'easy', category: ['animals'] },
  { id: 'e58', word: 'spider', difficulty: 'easy', category: ['animals'] },
  { id: 'e59', word: 'butterfly', difficulty: 'easy', category: ['animals'] },
  { id: 'e60', word: 'bee', difficulty: 'easy', category: ['animals'] },
  { id: 'e61', word: 'ant', difficulty: 'easy', category: ['animals'] },
  { id: 'e62', word: 'grass', difficulty: 'easy', category: ['nature'] },
  { id: 'e63', word: 'leaf', difficulty: 'easy', category: ['nature'] },
  { id: 'e64', word: 'rock', difficulty: 'easy', category: ['nature'] },
  { id: 'e65', word: 'mountain', difficulty: 'easy', category: ['nature'] },
  { id: 'e66', word: 'river', difficulty: 'easy', category: ['nature'] },
  { id: 'e67', word: 'ocean', difficulty: 'easy', category: ['nature'] },
  { id: 'e68', word: 'beach', difficulty: 'easy', category: ['nature'] },
  { id: 'e69', word: 'sand', difficulty: 'easy', category: ['nature'] },
  { id: 'e70', word: 'fire', difficulty: 'easy', category: ['nature', 'elements'] },
  { id: 'e71', word: 'ice', difficulty: 'easy', category: ['nature'] },
  { id: 'e72', word: 'wind', difficulty: 'easy', category: ['nature'] },
  { id: 'e73', word: 'rainbow', difficulty: 'easy', category: ['nature', 'weather'] },
  { id: 'e74', word: 'bridge', difficulty: 'easy', category: ['buildings'] },
  { id: 'e75', word: 'road', difficulty: 'easy', category: ['infrastructure'] },
  { id: 'e76', word: 'bike', difficulty: 'easy', category: ['transportation'] },
  { id: 'e77', word: 'bus', difficulty: 'easy', category: ['transportation'] },
  { id: 'e78', word: 'train', difficulty: 'easy', category: ['transportation'] },
  { id: 'e79', word: 'plane', difficulty: 'easy', category: ['transportation'] },
  { id: 'e80', word: 'boat', difficulty: 'easy', category: ['transportation'] },
  { id: 'e81', word: 'ship', difficulty: 'easy', category: ['transportation'] },
  { id: 'e82', word: 'helicopter', difficulty: 'easy', category: ['transportation'] },
  { id: 'e83', word: 'truck', difficulty: 'easy', category: ['transportation'] },
  { id: 'e84', word: 'taxi', difficulty: 'easy', category: ['transportation'] },
  { id: 'e85', word: 'school', difficulty: 'easy', category: ['buildings'] },
  { id: 'e86', word: 'hospital', difficulty: 'easy', category: ['buildings'] },
  { id: 'e87', word: 'church', difficulty: 'easy', category: ['buildings'] },
  { id: 'e88', word: 'store', difficulty: 'easy', category: ['buildings'] },
  { id: 'e89', word: 'bank', difficulty: 'easy', category: ['buildings'] },
  { id: 'e90', word: 'hotel', difficulty: 'easy', category: ['buildings'] },
  { id: 'e91', word: 'restaurant', difficulty: 'easy', category: ['buildings'] },
  { id: 'e92', word: 'library', difficulty: 'easy', category: ['buildings'] },
  { id: 'e93', word: 'park', difficulty: 'easy', category: ['places'] },
  { id: 'e94', word: 'zoo', difficulty: 'easy', category: ['places'] },
  { id: 'e95', word: 'farm', difficulty: 'easy', category: ['places'] },
  { id: 'e96', word: 'city', difficulty: 'easy', category: ['places'] },
  { id: 'e97', word: 'town', difficulty: 'easy', category: ['places'] },
  { id: 'e98', word: 'country', difficulty: 'easy', category: ['places'] },
  { id: 'e99', word: 'world', difficulty: 'easy', category: ['places'] },
  { id: 'e100', word: 'space', difficulty: 'easy', category: ['places'] },
  { id: 'e101', word: 'pen', difficulty: 'easy', category: ['objects'] },
  { id: 'e102', word: 'pencil', difficulty: 'easy', category: ['objects'] },
  { id: 'e103', word: 'paper', difficulty: 'easy', category: ['objects'] },
  { id: 'e104', word: 'scissors', difficulty: 'easy', category: ['objects'] },
  { id: 'e105', word: 'glue', difficulty: 'easy', category: ['objects'] },
  { id: 'e106', word: 'tape', difficulty: 'easy', category: ['objects'] },
  { id: 'e107', word: 'ruler', difficulty: 'easy', category: ['objects'] },
  { id: 'e108', word: 'eraser', difficulty: 'easy', category: ['objects'] },
  { id: 'e109', word: 'crayon', difficulty: 'easy', category: ['objects'] },
  { id: 'e110', word: 'paint', difficulty: 'easy', category: ['objects'] },
  { id: 'e111', word: 'brush', difficulty: 'easy', category: ['objects'] },
  { id: 'e112', word: 'camera', difficulty: 'easy', category: ['technology'] },
  { id: 'e113', word: 'computer', difficulty: 'easy', category: ['technology'] },
  { id: 'e114', word: 'television', difficulty: 'easy', category: ['technology'] },
  { id: 'e115', word: 'radio', difficulty: 'easy', category: ['technology'] },
  { id: 'e116', word: 'music', difficulty: 'easy', category: ['entertainment'] },
  { id: 'e117', word: 'song', difficulty: 'easy', category: ['entertainment'] },
  { id: 'e118', word: 'dance', difficulty: 'easy', category: ['entertainment'] },
  { id: 'e119', word: 'movie', difficulty: 'easy', category: ['entertainment'] },
  { id: 'e120', word: 'game', difficulty: 'easy', category: ['entertainment'] },
  { id: 'e121', word: 'toy', difficulty: 'easy', category: ['objects'] },
  { id: 'e122', word: 'doll', difficulty: 'easy', category: ['toys'] },
  { id: 'e123', word: 'robot', difficulty: 'easy', category: ['toys', 'technology'] },
  { id: 'e124', word: 'puzzle', difficulty: 'easy', category: ['toys'] },
  { id: 'e125', word: 'blocks', difficulty: 'easy', category: ['toys'] },
  { id: 'e126', word: 'kite', difficulty: 'easy', category: ['toys'] },
  { id: 'e127', word: 'balloon', difficulty: 'easy', category: ['objects'] },
  { id: 'e128', word: 'gift', difficulty: 'easy', category: ['objects'] },
  { id: 'e129', word: 'box', difficulty: 'easy', category: ['objects'] },
  { id: 'e130', word: 'bag', difficulty: 'easy', category: ['objects'] },
  { id: 'e131', word: 'basket', difficulty: 'easy', category: ['objects'] },
  { id: 'e132', word: 'bottle', difficulty: 'easy', category: ['objects'] },
  { id: 'e133', word: 'cup', difficulty: 'easy', category: ['objects'] },
  { id: 'e134', word: 'plate', difficulty: 'easy', category: ['objects'] },
  { id: 'e135', word: 'bowl', difficulty: 'easy', category: ['objects'] },
  { id: 'e136', word: 'spoon', difficulty: 'easy', category: ['objects'] },
  { id: 'e137', word: 'fork', difficulty: 'easy', category: ['objects'] },
  { id: 'e138', word: 'knife', difficulty: 'easy', category: ['objects'] },
  { id: 'e139', word: 'pot', difficulty: 'easy', category: ['objects'] },
  { id: 'e140', word: 'pan', difficulty: 'easy', category: ['objects'] },
  { id: 'e141', word: 'stove', difficulty: 'easy', category: ['appliances'] },
  { id: 'e142', word: 'oven', difficulty: 'easy', category: ['appliances'] },
  { id: 'e143', word: 'microwave', difficulty: 'easy', category: ['appliances'] },
  { id: 'e144', word: 'refrigerator', difficulty: 'easy', category: ['appliances'] },
  { id: 'e145', word: 'sink', difficulty: 'easy', category: ['fixtures'] },
  { id: 'e146', word: 'toilet', difficulty: 'easy', category: ['fixtures'] },
  { id: 'e147', word: 'shower', difficulty: 'easy', category: ['fixtures'] },
  { id: 'e148', word: 'bathtub', difficulty: 'easy', category: ['fixtures'] },
  { id: 'e149', word: 'towel', difficulty: 'easy', category: ['objects'] },
  { id: 'e150', word: 'soap', difficulty: 'easy', category: ['objects'] },
  { id: 'e151', word: 'shampoo', difficulty: 'easy', category: ['objects'] },
  { id: 'e152', word: 'toothbrush', difficulty: 'easy', category: ['objects'] },
  { id: 'e153', word: 'toothpaste', difficulty: 'easy', category: ['objects'] },
  { id: 'e154', word: 'mirror', difficulty: 'easy', category: ['objects'] },
  { id: 'e155', word: 'comb', difficulty: 'easy', category: ['objects'] },
  { id: 'e156', word: 'hair', difficulty: 'easy', category: ['body'] },
  { id: 'e157', word: 'face', difficulty: 'easy', category: ['body'] },
  { id: 'e158', word: 'teeth', difficulty: 'easy', category: ['body'] },
  { id: 'e159', word: 'tongue', difficulty: 'easy', category: ['body'] },
  { id: 'e160', word: 'finger', difficulty: 'easy', category: ['body'] },
  { id: 'e161', word: 'toe', difficulty: 'easy', category: ['body'] },
  { id: 'e162', word: 'arm', difficulty: 'easy', category: ['body'] },
  { id: 'e163', word: 'leg', difficulty: 'easy', category: ['body'] },
  { id: 'e164', word: 'knee', difficulty: 'easy', category: ['body'] },
  { id: 'e165', word: 'elbow', difficulty: 'easy', category: ['body'] },
  { id: 'e166', word: 'shoulder', difficulty: 'easy', category: ['body'] },
  { id: 'e167', word: 'neck', difficulty: 'easy', category: ['body'] },
  { id: 'e168', word: 'back', difficulty: 'easy', category: ['body'] },
  { id: 'e169', word: 'stomach', difficulty: 'easy', category: ['body'] },
  { id: 'e170', word: 'chest', difficulty: 'easy', category: ['body'] },
  { id: 'e171', word: 'head', difficulty: 'easy', category: ['body'] },
  { id: 'e172', word: 'brain', difficulty: 'easy', category: ['body'] },
  { id: 'e173', word: 'blood', difficulty: 'easy', category: ['body'] },
  { id: 'e174', word: 'bone', difficulty: 'easy', category: ['body'] },
  { id: 'e175', word: 'skin', difficulty: 'easy', category: ['body'] },
  { id: 'e176', word: 'happy', difficulty: 'easy', category: ['emotions'] },
  { id: 'e177', word: 'sad', difficulty: 'easy', category: ['emotions'] },
  { id: 'e178', word: 'angry', difficulty: 'easy', category: ['emotions'] },
  { id: 'e179', word: 'scared', difficulty: 'easy', category: ['emotions'] },
  { id: 'e180', word: 'love', difficulty: 'easy', category: ['emotions'] },
  { id: 'e181', word: 'friend', difficulty: 'easy', category: ['people'] },
  { id: 'e182', word: 'family', difficulty: 'easy', category: ['people'] },
  { id: 'e183', word: 'mother', difficulty: 'easy', category: ['people'] },
  { id: 'e184', word: 'father', difficulty: 'easy', category: ['people'] },
  { id: 'e185', word: 'sister', difficulty: 'easy', category: ['people'] },
  { id: 'e186', word: 'brother', difficulty: 'easy', category: ['people'] },
  { id: 'e187', word: 'baby', difficulty: 'easy', category: ['people'] },
  { id: 'e188', word: 'child', difficulty: 'easy', category: ['people'] },
  { id: 'e189', word: 'man', difficulty: 'easy', category: ['people'] },
  { id: 'e190', word: 'woman', difficulty: 'easy', category: ['people'] },
  { id: 'e191', word: 'boy', difficulty: 'easy', category: ['people'] },
  { id: 'e192', word: 'girl', difficulty: 'easy', category: ['people'] },
  { id: 'e193', word: 'teacher', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e194', word: 'doctor', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e195', word: 'nurse', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e196', word: 'police', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e197', word: 'firefighter', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e198', word: 'chef', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e199', word: 'farmer', difficulty: 'easy', category: ['people', 'occupations'] },
  { id: 'e200', word: 'student', difficulty: 'easy', category: ['people', 'occupations'] },

  // Medium words (200)
  { id: 'm1', word: 'bicycle', difficulty: 'medium', category: ['transportation'] },
  { id: 'm2', word: 'waterfall', difficulty: 'medium', category: ['nature'] },
  { id: 'm3', word: 'birthday cake', difficulty: 'medium', category: ['food', 'celebrations'] },
  { id: 'm4', word: 'telescope', difficulty: 'medium', category: ['technology', 'science'] },
  { id: 'm5', word: 'lighthouse', difficulty: 'medium', category: ['buildings'] },
  { id: 'm6', word: 'volcano', difficulty: 'medium', category: ['nature'] },
  { id: 'm7', word: 'skateboard', difficulty: 'medium', category: ['sports'] },
  { id: 'm8', word: 'microscope', difficulty: 'medium', category: ['technology', 'science'] },
  { id: 'm9', word: 'compass', difficulty: 'medium', category: ['tools'] },
  { id: 'm10', word: 'thermometer', difficulty: 'medium', category: ['tools', 'science'] },
  { id: 'm11', word: 'calculator', difficulty: 'medium', category: ['technology'] },
  { id: 'm12', word: 'keyboard', difficulty: 'medium', category: ['technology'] },
  { id: 'm13', word: 'headphones', difficulty: 'medium', category: ['technology'] },
  { id: 'm14', word: 'backpack', difficulty: 'medium', category: ['objects'] },
  { id: 'm15', word: 'umbrella', difficulty: 'medium', category: ['objects'] },
  { id: 'm16', word: 'sunglasses', difficulty: 'medium', category: ['accessories'] },
  { id: 'm17', word: 'wristwatch', difficulty: 'medium', category: ['accessories'] },
  { id: 'm18', word: 'necklace', difficulty: 'medium', category: ['accessories'] },
  { id: 'm19', word: 'bracelet', difficulty: 'medium', category: ['accessories'] },
  { id: 'm20', word: 'earrings', difficulty: 'medium', category: ['accessories'] },
  { id: 'm21', word: 'wallet', difficulty: 'medium', category: ['objects'] },
  { id: 'm22', word: 'passport', difficulty: 'medium', category: ['documents'] },
  { id: 'm23', word: 'suitcase', difficulty: 'medium', category: ['objects'] },
  { id: 'm24', word: 'airplane ticket', difficulty: 'medium', category: ['documents'] },
  { id: 'm25', word: 'hotel room', difficulty: 'medium', category: ['places'] },
  { id: 'm26', word: 'swimming pool', difficulty: 'medium', category: ['places'] },
  { id: 'm27', word: 'tennis court', difficulty: 'medium', category: ['sports', 'places'] },
  { id: 'm28', word: 'basketball hoop', difficulty: 'medium', category: ['sports'] },
  { id: 'm29', word: 'soccer goal', difficulty: 'medium', category: ['sports'] },
  { id: 'm30', word: 'baseball bat', difficulty: 'medium', category: ['sports'] },
  { id: 'm31', word: 'golf club', difficulty: 'medium', category: ['sports'] },
  { id: 'm32', word: 'bowling ball', difficulty: 'medium', category: ['sports'] },
  { id: 'm33', word: 'ice skates', difficulty: 'medium', category: ['sports'] },
  { id: 'm34', word: 'roller skates', difficulty: 'medium', category: ['sports'] },
  { id: 'm35', word: 'surfboard', difficulty: 'medium', category: ['sports'] },
  { id: 'm36', word: 'snowboard', difficulty: 'medium', category: ['sports'] },
  { id: 'm37', word: 'parachute', difficulty: 'medium', category: ['sports', 'equipment'] },
  { id: 'm38', word: 'hot air balloon', difficulty: 'medium', category: ['transportation'] },
  { id: 'm39', word: 'submarine', difficulty: 'medium', category: ['transportation'] },
  { id: 'm40', word: 'rocket ship', difficulty: 'medium', category: ['transportation', 'space'] },
  { id: 'm41', word: 'space station', difficulty: 'medium', category: ['space'] },
  { id: 'm42', word: 'astronaut', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm43', word: 'alien', difficulty: 'medium', category: ['fantasy'] },
  { id: 'm44', word: 'dinosaur', difficulty: 'medium', category: ['animals', 'history'] },
  { id: 'm45', word: 'skeleton', difficulty: 'medium', category: ['body', 'halloween'] },
  { id: 'm46', word: 'vampire', difficulty: 'medium', category: ['fantasy', 'halloween'] },
  { id: 'm47', word: 'werewolf', difficulty: 'medium', category: ['fantasy', 'halloween'] },
  { id: 'm48', word: 'witch', difficulty: 'medium', category: ['fantasy', 'halloween'] },
  { id: 'm49', word: 'wizard', difficulty: 'medium', category: ['fantasy'] },
  { id: 'm50', word: 'dragon', difficulty: 'medium', category: ['fantasy'] },
  { id: 'm51', word: 'unicorn', difficulty: 'medium', category: ['fantasy'] },
  { id: 'm52', word: 'mermaid', difficulty: 'medium', category: ['fantasy'] },
  { id: 'm53', word: 'fairy', difficulty: 'medium', category: ['fantasy'] },
  { id: 'm54', word: 'castle', difficulty: 'medium', category: ['buildings', 'fantasy'] },
  { id: 'm55', word: 'knight', difficulty: 'medium', category: ['people', 'fantasy'] },
  { id: 'm56', word: 'princess', difficulty: 'medium', category: ['people', 'fantasy'] },
  { id: 'm57', word: 'prince', difficulty: 'medium', category: ['people', 'fantasy'] },
  { id: 'm58', word: 'king', difficulty: 'medium', category: ['people', 'fantasy'] },
  { id: 'm59', word: 'queen', difficulty: 'medium', category: ['people', 'fantasy'] },
  { id: 'm60', word: 'crown', difficulty: 'medium', category: ['objects', 'fantasy'] },
  { id: 'm61', word: 'treasure chest', difficulty: 'medium', category: ['objects', 'fantasy'] },
  { id: 'm62', word: 'pirate ship', difficulty: 'medium', category: ['transportation', 'fantasy'] },
  { id: 'm63', word: 'treasure map', difficulty: 'medium', category: ['objects', 'fantasy'] },
  { id: 'm64', word: 'compass rose', difficulty: 'medium', category: ['navigation'] },
  { id: 'm65', word: 'anchor', difficulty: 'medium', category: ['nautical'] },
  { id: 'm66', word: 'sailboat', difficulty: 'medium', category: ['transportation'] },
  { id: 'm67', word: 'yacht', difficulty: 'medium', category: ['transportation'] },
  { id: 'm68', word: 'cruise ship', difficulty: 'medium', category: ['transportation'] },
  { id: 'm69', word: 'lifeboat', difficulty: 'medium', category: ['transportation', 'safety'] },
  { id: 'm70', word: 'life jacket', difficulty: 'medium', category: ['safety'] },
  { id: 'm71', word: 'fire extinguisher', difficulty: 'medium', category: ['safety'] },
  { id: 'm72', word: 'smoke detector', difficulty: 'medium', category: ['safety'] },
  { id: 'm73', word: 'first aid kit', difficulty: 'medium', category: ['safety', 'medical'] },
  { id: 'm74', word: 'ambulance', difficulty: 'medium', category: ['transportation', 'medical'] },
  { id: 'm75', word: 'stretcher', difficulty: 'medium', category: ['medical'] },
  { id: 'm76', word: 'wheelchair', difficulty: 'medium', category: ['medical'] },
  { id: 'm77', word: 'crutches', difficulty: 'medium', category: ['medical'] },
  { id: 'm78', word: 'bandage', difficulty: 'medium', category: ['medical'] },
  { id: 'm79', word: 'stethoscope', difficulty: 'medium', category: ['medical'] },
  { id: 'm80', word: 'syringe', difficulty: 'medium', category: ['medical'] },
  { id: 'm81', word: 'medicine bottle', difficulty: 'medium', category: ['medical'] },
  { id: 'm82', word: 'prescription', difficulty: 'medium', category: ['medical', 'documents'] },
  { id: 'm83', word: 'x-ray', difficulty: 'medium', category: ['medical'] },
  { id: 'm84', word: 'dentist chair', difficulty: 'medium', category: ['medical'] },
  { id: 'm85', word: 'toothache', difficulty: 'medium', category: ['medical'] },
  { id: 'm86', word: 'headache', difficulty: 'medium', category: ['medical'] },
  { id: 'm87', word: 'fever', difficulty: 'medium', category: ['medical'] },
  { id: 'm88', word: 'sneeze', difficulty: 'medium', category: ['actions'] },
  { id: 'm89', word: 'cough', difficulty: 'medium', category: ['actions'] },
  { id: 'm90', word: 'yawn', difficulty: 'medium', category: ['actions'] },
  { id: 'm91', word: 'stretch', difficulty: 'medium', category: ['actions'] },
  { id: 'm92', word: 'exercise', difficulty: 'medium', category: ['actions', 'health'] },
  { id: 'm93', word: 'yoga pose', difficulty: 'medium', category: ['health', 'fitness'] },
  { id: 'm94', word: 'meditation', difficulty: 'medium', category: ['health', 'wellness'] },
  { id: 'm95', word: 'treadmill', difficulty: 'medium', category: ['fitness', 'equipment'] },
  { id: 'm96', word: 'dumbbell', difficulty: 'medium', category: ['fitness', 'equipment'] },
  { id: 'm97', word: 'jump rope', difficulty: 'medium', category: ['fitness', 'equipment'] },
  { id: 'm98', word: 'hula hoop', difficulty: 'medium', category: ['toys', 'fitness'] },
  { id: 'm99', word: 'trampoline', difficulty: 'medium', category: ['equipment', 'fun'] },
  { id: 'm100', word: 'swing set', difficulty: 'medium', category: ['playground'] },
  { id: 'm101', word: 'slide', difficulty: 'medium', category: ['playground'] },
  { id: 'm102', word: 'seesaw', difficulty: 'medium', category: ['playground'] },
  { id: 'm103', word: 'merry-go-round', difficulty: 'medium', category: ['playground'] },
  { id: 'm104', word: 'sandbox', difficulty: 'medium', category: ['playground'] },
  { id: 'm105', word: 'jungle gym', difficulty: 'medium', category: ['playground'] },
  { id: 'm106', word: 'monkey bars', difficulty: 'medium', category: ['playground'] },
  { id: 'm107', word: 'hopscotch', difficulty: 'medium', category: ['games'] },
  { id: 'm108', word: 'hide and seek', difficulty: 'medium', category: ['games'] },
  { id: 'm109', word: 'tag', difficulty: 'medium', category: ['games'] },
  { id: 'm110', word: 'board game', difficulty: 'medium', category: ['games'] },
  { id: 'm111', word: 'chess board', difficulty: 'medium', category: ['games'] },
  { id: 'm112', word: 'checkers', difficulty: 'medium', category: ['games'] },
  { id: 'm113', word: 'playing cards', difficulty: 'medium', category: ['games'] },
  { id: 'm114', word: 'dice', difficulty: 'medium', category: ['games'] },
  { id: 'm115', word: 'dominoes', difficulty: 'medium', category: ['games'] },
  { id: 'm116', word: 'jigsaw puzzle', difficulty: 'medium', category: ['games'] },
  { id: 'm117', word: 'crossword puzzle', difficulty: 'medium', category: ['games'] },
  { id: 'm118', word: 'sudoku', difficulty: 'medium', category: ['games'] },
  { id: 'm119', word: 'video game controller', difficulty: 'medium', category: ['technology', 'games'] },
  { id: 'm120', word: 'joystick', difficulty: 'medium', category: ['technology', 'games'] },
  { id: 'm121', word: 'arcade machine', difficulty: 'medium', category: ['technology', 'games'] },
  { id: 'm122', word: 'pinball machine', difficulty: 'medium', category: ['games'] },
  { id: 'm123', word: 'slot machine', difficulty: 'medium', category: ['games', 'gambling'] },
  { id: 'm124', word: 'roulette wheel', difficulty: 'medium', category: ['games', 'gambling'] },
  { id: 'm125', word: 'poker chips', difficulty: 'medium', category: ['games', 'gambling'] },
  { id: 'm126', word: 'trophy', difficulty: 'medium', category: ['awards'] },
  { id: 'm127', word: 'medal', difficulty: 'medium', category: ['awards'] },
  { id: 'm128', word: 'ribbon', difficulty: 'medium', category: ['awards'] },
  { id: 'm129', word: 'certificate', difficulty: 'medium', category: ['documents', 'awards'] },
  { id: 'm130', word: 'diploma', difficulty: 'medium', category: ['documents', 'education'] },
  { id: 'm131', word: 'graduation cap', difficulty: 'medium', category: ['education'] },
  { id: 'm132', word: 'school bus', difficulty: 'medium', category: ['transportation', 'education'] },
  { id: 'm133', word: 'blackboard', difficulty: 'medium', category: ['education'] },
  { id: 'm134', word: 'whiteboard', difficulty: 'medium', category: ['education'] },
  { id: 'm135', word: 'projector', difficulty: 'medium', category: ['technology', 'education'] },
  { id: 'm136', word: 'globe', difficulty: 'medium', category: ['education', 'geography'] },
  { id: 'm137', word: 'atlas', difficulty: 'medium', category: ['books', 'geography'] },
  { id: 'm138', word: 'encyclopedia', difficulty: 'medium', category: ['books', 'education'] },
  { id: 'm139', word: 'dictionary', difficulty: 'medium', category: ['books', 'education'] },
  { id: 'm140', word: 'thesaurus', difficulty: 'medium', category: ['books', 'education'] },
  { id: 'm141', word: 'bookmark', difficulty: 'medium', category: ['objects'] },
  { id: 'm142', word: 'reading glasses', difficulty: 'medium', category: ['accessories'] },
  { id: 'm143', word: 'magnifying glass', difficulty: 'medium', category: ['tools'] },
  { id: 'm144', word: 'binoculars', difficulty: 'medium', category: ['tools'] },
  { id: 'm145', word: 'periscope', difficulty: 'medium', category: ['tools'] },
  { id: 'm146', word: 'kaleidoscope', difficulty: 'medium', category: ['toys'] },
  { id: 'm147', word: 'prism', difficulty: 'medium', category: ['science'] },
  { id: 'm148', word: 'test tube', difficulty: 'medium', category: ['science'] },
  { id: 'm149', word: 'beaker', difficulty: 'medium', category: ['science'] },
  { id: 'm150', word: 'bunsen burner', difficulty: 'medium', category: ['science'] },
  { id: 'm151', word: 'periodic table', difficulty: 'medium', category: ['science', 'education'] },
  { id: 'm152', word: 'solar system', difficulty: 'medium', category: ['space', 'science'] },
  { id: 'm153', word: 'constellation', difficulty: 'medium', category: ['space', 'science'] },
  { id: 'm154', word: 'shooting star', difficulty: 'medium', category: ['space'] },
  { id: 'm155', word: 'comet', difficulty: 'medium', category: ['space'] },
  { id: 'm156', word: 'asteroid', difficulty: 'medium', category: ['space'] },
  { id: 'm157', word: 'galaxy', difficulty: 'medium', category: ['space'] },
  { id: 'm158', word: 'black hole', difficulty: 'medium', category: ['space'] },
  { id: 'm159', word: 'satellite', difficulty: 'medium', category: ['space', 'technology'] },
  { id: 'm160', word: 'space shuttle', difficulty: 'medium', category: ['space', 'transportation'] },
  { id: 'm161', word: 'control tower', difficulty: 'medium', category: ['buildings'] },
  { id: 'm162', word: 'runway', difficulty: 'medium', category: ['infrastructure'] },
  { id: 'm163', word: 'baggage claim', difficulty: 'medium', category: ['places'] },
  { id: 'm164', word: 'departure board', difficulty: 'medium', category: ['information'] },
  { id: 'm165', word: 'boarding pass', difficulty: 'medium', category: ['documents'] },
  { id: 'm166', word: 'flight attendant', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm167', word: 'pilot', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm168', word: 'air traffic controller', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm169', word: 'mechanic', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm170', word: 'electrician', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm171', word: 'plumber', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm172', word: 'carpenter', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm173', word: 'architect', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm174', word: 'engineer', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm175', word: 'scientist', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm176', word: 'researcher', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm177', word: 'professor', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm178', word: 'librarian', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm179', word: 'accountant', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm180', word: 'lawyer', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm181', word: 'judge', difficulty: 'medium', category: ['people', 'occupations'] },
  { id: 'm182', word: 'courtroom', difficulty: 'medium', category: ['places'] },
  { id: 'm183', word: 'gavel', difficulty: 'medium', category: ['objects'] },
  { id: 'm184', word: 'scales of justice', difficulty: 'medium', category: ['symbols'] },
  { id: 'm185', word: 'handcuffs', difficulty: 'medium', category: ['objects'] },
  { id: 'm186', word: 'jail cell', difficulty: 'medium', category: ['places'] },
  { id: 'm187', word: 'security camera', difficulty: 'medium', category: ['technology', 'safety'] },
  { id: 'm188', word: 'metal detector', difficulty: 'medium', category: ['technology', 'safety'] },
  { id: 'm189', word: 'fingerprint', difficulty: 'medium', category: ['identification'] },
  { id: 'm190', word: 'magnifying glass', difficulty: 'medium', category: ['tools'] },
  { id: 'm191', word: 'evidence', difficulty: 'medium', category: ['law'] },
  { id: 'm192', word: 'witness stand', difficulty: 'medium', category: ['law', 'places'] },
  { id: 'm193', word: 'jury box', difficulty: 'medium', category: ['law', 'places'] },
  { id: 'm194', word: 'briefcase', difficulty: 'medium', category: ['objects'] },
  { id: 'm195', word: 'filing cabinet', difficulty: 'medium', category: ['furniture'] },
  { id: 'm196', word: 'paper clip', difficulty: 'medium', category: ['objects'] },
  { id: 'm197', word: 'stapler', difficulty: 'medium', category: ['objects'] },
  { id: 'm198', word: 'hole punch', difficulty: 'medium', category: ['objects'] },
  { id: 'm199', word: 'shredder', difficulty: 'medium', category: ['office equipment'] },
  { id: 'm200', word: 'photocopier', difficulty: 'medium', category: ['office equipment'] },

  // Hard words (100)
  { id: 'h1', word: 'democracy', difficulty: 'hard', category: ['concepts', 'politics'] },
  { id: 'h2', word: 'photosynthesis', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h3', word: 'anxiety', difficulty: 'hard', category: ['emotions', 'psychology'] },
  { id: 'h4', word: 'philosophy', difficulty: 'hard', category: ['concepts', 'education'] },
  { id: 'h5', word: 'metamorphosis', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h6', word: 'consciousness', difficulty: 'hard', category: ['concepts', 'psychology'] },
  { id: 'h7', word: 'evolution', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h8', word: 'gravity', difficulty: 'hard', category: ['science', 'physics'] },
  { id: 'h9', word: 'relativity', difficulty: 'hard', category: ['science', 'physics'] },
  { id: 'h10', word: 'quantum physics', difficulty: 'hard', category: ['science', 'physics'] },
  { id: 'h11', word: 'ecosystem', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h12', word: 'biodiversity', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h13', word: 'sustainability', difficulty: 'hard', category: ['concepts', 'environment'] },
  { id: 'h14', word: 'globalization', difficulty: 'hard', category: ['concepts', 'economics'] },
  { id: 'h15', word: 'inflation', difficulty: 'hard', category: ['economics'] },
  { id: 'h16', word: 'recession', difficulty: 'hard', category: ['economics'] },
  { id: 'h17', word: 'cryptocurrency', difficulty: 'hard', category: ['technology', 'economics'] },
  { id: 'h18', word: 'artificial intelligence', difficulty: 'hard', category: ['technology'] },
  { id: 'h19', word: 'machine learning', difficulty: 'hard', category: ['technology'] },
  { id: 'h20', word: 'algorithm', difficulty: 'hard', category: ['technology', 'mathematics'] },
  { id: 'h21', word: 'encryption', difficulty: 'hard', category: ['technology', 'security'] },
  { id: 'h22', word: 'blockchain', difficulty: 'hard', category: ['technology'] },
  { id: 'h23', word: 'virtual reality', difficulty: 'hard', category: ['technology'] },
  { id: 'h24', word: 'augmented reality', difficulty: 'hard', category: ['technology'] },
  { id: 'h25', word: 'nanotechnology', difficulty: 'hard', category: ['technology', 'science'] },
  { id: 'h26', word: 'biotechnology', difficulty: 'hard', category: ['technology', 'science'] },
  { id: 'h27', word: 'genetic engineering', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h28', word: 'cloning', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h29', word: 'stem cells', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h30', word: 'antibiotics', difficulty: 'hard', category: ['medicine'] },
  { id: 'h31', word: 'vaccination', difficulty: 'hard', category: ['medicine'] },
  { id: 'h32', word: 'pandemic', difficulty: 'hard', category: ['medicine', 'health'] },
  { id: 'h33', word: 'epidemic', difficulty: 'hard', category: ['medicine', 'health'] },
  { id: 'h34', word: 'quarantine', difficulty: 'hard', category: ['health', 'safety'] },
  { id: 'h35', word: 'immunity', difficulty: 'hard', category: ['health', 'biology'] },
  { id: 'h36', word: 'metabolism', difficulty: 'hard', category: ['biology', 'health'] },
  { id: 'h37', word: 'neuroscience', difficulty: 'hard', category: ['science', 'biology'] },
  { id: 'h38', word: 'psychology', difficulty: 'hard', category: ['science', 'behavior'] },
  { id: 'h39', word: 'sociology', difficulty: 'hard', category: ['science', 'society'] },
  { id: 'h40', word: 'anthropology', difficulty: 'hard', category: ['science', 'culture'] },
  { id: 'h41', word: 'archaeology', difficulty: 'hard', category: ['science', 'history'] },
  { id: 'h42', word: 'paleontology', difficulty: 'hard', category: ['science', 'history'] },
  { id: 'h43', word: 'geology', difficulty: 'hard', category: ['science', 'earth'] },
  { id: 'h44', word: 'meteorology', difficulty: 'hard', category: ['science', 'weather'] },
  { id: 'h45', word: 'astronomy', difficulty: 'hard', category: ['science', 'space'] },
  { id: 'h46', word: 'astrophysics', difficulty: 'hard', category: ['science', 'space'] },
  { id: 'h47', word: 'cosmology', difficulty: 'hard', category: ['science', 'space'] },
  { id: 'h48', word: 'supernova', difficulty: 'hard', category: ['space', 'astronomy'] },
  { id: 'h49', word: 'nebula', difficulty: 'hard', category: ['space', 'astronomy'] },
  { id: 'h50', word: 'dark matter', difficulty: 'hard', category: ['space', 'physics'] },
  { id: 'h51', word: 'time travel', difficulty: 'hard', category: ['concepts', 'science fiction'] },
  { id: 'h52', word: 'parallel universe', difficulty: 'hard', category: ['concepts', 'science fiction'] },
  { id: 'h53', word: 'teleportation', difficulty: 'hard', category: ['concepts', 'science fiction'] },
  { id: 'h54', word: 'telepathy', difficulty: 'hard', category: ['concepts', 'psychology'] },
  { id: 'h55', word: 'meditation', difficulty: 'hard', category: ['wellness', 'mindfulness'] },
  { id: 'h56', word: 'mindfulness', difficulty: 'hard', category: ['wellness', 'psychology'] },
  { id: 'h57', word: 'empathy', difficulty: 'hard', category: ['emotions', 'psychology'] },
  { id: 'h58', word: 'compassion', difficulty: 'hard', category: ['emotions', 'values'] },
  { id: 'h59', word: 'resilience', difficulty: 'hard', category: ['psychology', 'character'] },
  { id: 'h60', word: 'perseverance', difficulty: 'hard', category: ['character', 'values'] },
  { id: 'h61', word: 'integrity', difficulty: 'hard', category: ['character', 'values'] },
  { id: 'h62', word: 'justice', difficulty: 'hard', category: ['concepts', 'law'] },
  { id: 'h63', word: 'freedom', difficulty: 'hard', category: ['concepts', 'rights'] },
  { id: 'h64', word: 'equality', difficulty: 'hard', category: ['concepts', 'rights'] },
  { id: 'h65', word: 'diversity', difficulty: 'hard', category: ['concepts', 'society'] },
  { id: 'h66', word: 'inclusion', difficulty: 'hard', category: ['concepts', 'society'] },
  { id: 'h67', word: 'discrimination', difficulty: 'hard', category: ['concepts', 'society'] },
  { id: 'h68', word: 'prejudice', difficulty: 'hard', category: ['concepts', 'psychology'] },
  { id: 'h69', word: 'stereotype', difficulty: 'hard', category: ['concepts', 'psychology'] },
  { id: 'h70', word: 'culture', difficulty: 'hard', category: ['concepts', 'society'] },
  { id: 'h71', word: 'tradition', difficulty: 'hard', category: ['concepts', 'culture'] },
  { id: 'h72', word: 'heritage', difficulty: 'hard', category: ['concepts', 'culture'] },
  { id: 'h73', word: 'civilization', difficulty: 'hard', category: ['history', 'society'] },
  { id: 'h74', word: 'revolution', difficulty: 'hard', category: ['history', 'politics'] },
  { id: 'h75', word: 'constitution', difficulty: 'hard', category: ['law', 'politics'] },
  { id: 'h76', word: 'amendment', difficulty: 'hard', category: ['law', 'politics'] },
  { id: 'h77', word: 'legislation', difficulty: 'hard', category: ['law', 'politics'] },
  { id: 'h78', word: 'bureaucracy', difficulty: 'hard', category: ['government', 'politics'] },
  { id: 'h79', word: 'diplomacy', difficulty: 'hard', category: ['politics', 'international'] },
  { id: 'h80', word: 'negotiation', difficulty: 'hard', category: ['communication', 'business'] },
  { id: 'h81', word: 'compromise', difficulty: 'hard', category: ['communication', 'resolution'] },
  { id: 'h82', word: 'consensus', difficulty: 'hard', category: ['communication', 'agreement'] },
  { id: 'h83', word: 'collaboration', difficulty: 'hard', category: ['teamwork', 'business'] },
  { id: 'h84', word: 'innovation', difficulty: 'hard', category: ['business', 'creativity'] },
  { id: 'h85', word: 'entrepreneurship', difficulty: 'hard', category: ['business'] },
  { id: 'h86', word: 'investment', difficulty: 'hard', category: ['business', 'finance'] },
  { id: 'h87', word: 'portfolio', difficulty: 'hard', category: ['business', 'finance'] },
  { id: 'h88', word: 'dividend', difficulty: 'hard', category: ['finance'] },
  { id: 'h89', word: 'mortgage', difficulty: 'hard', category: ['finance', 'real estate'] },
  { id: 'h90', word: 'insurance', difficulty: 'hard', category: ['finance', 'protection'] },
  { id: 'h91', word: 'liability', difficulty: 'hard', category: ['finance', 'law'] },
  { id: 'h92', word: 'bankruptcy', difficulty: 'hard', category: ['finance', 'law'] },
  { id: 'h93', word: 'foreclosure', difficulty: 'hard', category: ['finance', 'real estate'] },
  { id: 'h94', word: 'jurisdiction', difficulty: 'hard', category: ['law'] },
  { id: 'h95', word: 'testimony', difficulty: 'hard', category: ['law'] },
  { id: 'h96', word: 'verdict', difficulty: 'hard', category: ['law'] },
  { id: 'h97', word: 'appeal', difficulty: 'hard', category: ['law'] },
  { id: 'h98', word: 'precedent', difficulty: 'hard', category: ['law'] },
  { id: 'h99', word: 'litigation', difficulty: 'hard', category: ['law'] },
  { id: 'h100', word: 'arbitration', difficulty: 'hard', category: ['law', 'resolution'] }
];